#!/bin/bash
# Splunk Slack Alert Action 자동 설치 스크립트
# Purpose: Install custom Slack alert action to Splunk

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Splunk Slack Alert Action 설치${NC}"
echo -e "${GREEN}  (Splunkbase 공식 앱 slack_alerts v2.3.2)${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}❌ Error: 이 스크립트는 sudo로 실행해야 합니다.${NC}"
  echo "   Usage: sudo $0"
  exit 1
fi

# Splunk 설치 경로 찾기
SPLUNK_HOME=${SPLUNK_HOME:-/opt/splunk}

if [ ! -d "$SPLUNK_HOME" ]; then
  echo -e "${YELLOW}⚠️  SPLUNK_HOME이 $SPLUNK_HOME에 없습니다.${NC}"
  read -r -p "Splunk 설치 경로를 입력하세요: " CUSTOM_PATH
  SPLUNK_HOME=$CUSTOM_PATH
fi

if [ ! -d "$SPLUNK_HOME" ]; then
  echo -e "${RED}❌ Error: Splunk가 설치되지 않았습니다: $SPLUNK_HOME${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Splunk 설치 확인: $SPLUNK_HOME${NC}\n"

# 현재 스크립트 디렉토리
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

# Slack 앱 파일 확인
SLACK_APP_TGZ="$PROJECT_ROOT/plugins/slack-notification-alert_232.tgz"

if [ ! -f "$SLACK_APP_TGZ" ]; then
  echo -e "${RED}❌ Error: Slack 앱 파일을 찾을 수 없습니다: $SLACK_APP_TGZ${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Slack 앱 파일 확인: $(basename "$SLACK_APP_TGZ")${NC}\n"

# 1. Splunk 앱 설치
echo -e "${YELLOW}📦 1/4: Slack Notification Alert 앱 설치 중...${NC}"

APPS_DIR="$SPLUNK_HOME/etc/apps"
mkdir -p "$APPS_DIR"

# 기존 slack_alerts 앱 제거 (있다면)
if [ -d "$APPS_DIR/slack_alerts" ]; then
  echo -e "${YELLOW}   ⚠️  기존 slack_alerts 앱 제거 중...${NC}"
  rm -rf "$APPS_DIR/slack_alerts"
fi

# 앱 압축 해제
tar -xzf "$SLACK_APP_TGZ" -C "$APPS_DIR"

echo -e "${GREEN}   ✅ 설치 완료: $APPS_DIR/slack_alerts${NC}\n"

# 2. Slack 앱 설정
echo -e "${YELLOW}⚙️  2/4: Slack 앱 설정 중...${NC}"

LOCAL_DIR="$APPS_DIR/slack_alerts/local"
mkdir -p "$LOCAL_DIR"

# Webhook URL 입력 받기
echo -e "${YELLOW}🔗 Slack Webhook URL을 입력하세요:${NC}"
read -r -p "URL: " WEBHOOK_URL

if [[ ! "$WEBHOOK_URL" =~ ^https://hooks\.slack\.com/services/ ]]; then
  echo -e "${RED}❌ Error: 유효하지 않은 Webhook URL입니다.${NC}"
  echo "   예시: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXX"
  exit 1
fi

# 채널 입력 받기
read -r -p "Default 채널 (기본값: #splunk-alerts): " SLACK_CHANNEL
SLACK_CHANNEL=${SLACK_CHANNEL:-#splunk-alerts}

# alert_actions.conf 생성 (slack_alerts 앱용)
cat > "$LOCAL_DIR/alert_actions.conf" << EOF
# Slack Alert Actions 설정
# Generated by install-slack-alert.sh

[slack]
param.webhook_url = $WEBHOOK_URL
param.channel = $SLACK_CHANNEL
param.from_user = Splunk FortiGate Alert
param.message = Alert: \$name\$ triggered at \$trigger_time\$
EOF

echo -e "${GREEN}   ✅ 설정 파일 생성: $LOCAL_DIR/alert_actions.conf${NC}\n"

# 3. 권한 설정
echo -e "${YELLOW}🔒 3/4: 권한 설정 중...${NC}"

chown -R splunk:splunk "$APPS_DIR/slack_alerts" 2>/dev/null || \
chown -R "$SUDO_USER":"$SUDO_USER" "$APPS_DIR/slack_alerts"

echo -e "${GREEN}   ✅ 권한 설정 완료${NC}\n"

# 4. 연결 테스트
echo -e "${YELLOW}🧪 4/4: Slack 연결 테스트 중...${NC}"

# curl로 webhook 테스트
TEST_PAYLOAD='{"text":"✅ Splunk Slack Alert 설치 완료 테스트"}'
if curl -X POST -H 'Content-Type: application/json' -d "$TEST_PAYLOAD" "$WEBHOOK_URL" 2>/dev/null; then
  echo -e "${GREEN}   ✅ Slack 연결 테스트 성공${NC}"
else
  echo -e "${YELLOW}   ⚠️  테스트 실패. Webhook URL을 확인하세요.${NC}"
fi

echo ""

# Splunk 재시작 안내
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ 설치 완료!${NC}\n"
echo -e "${YELLOW}📌 다음 단계:${NC}"
echo ""
echo "1. Splunk 재시작:"
echo "   sudo $SPLUNK_HOME/bin/splunk restart"
echo ""
echo "2. Splunk Web UI에서 확인:"
echo "   Settings → Alert Actions → 'Slack' 확인 (slack_alerts 앱)"
echo ""
echo "3. 대시보드에서 Alert 생성:"
echo "   대시보드 패널 → Save As Alert → Alert Action: Slack"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# 재시작 여부 물어보기
read -r -p "지금 Splunk를 재시작하시겠습니까? (y/N): " RESTART
if [[ "$RESTART" =~ ^[Yy]$ ]]; then
  echo -e "\n${YELLOW}♻️  Splunk 재시작 중...${NC}"
  "$SPLUNK_HOME/bin/splunk" restart
  echo -e "${GREEN}✅ Splunk 재시작 완료${NC}"
else
  echo -e "\n${YELLOW}⚠️  나중에 수동으로 Splunk를 재시작하세요:${NC}"
  echo "   sudo $SPLUNK_HOME/bin/splunk restart"
fi

echo ""
echo -e "${GREEN}🎉 설치 성공!${NC}"
