#!/bin/bash
#
# Splunk Issues Diagnostic Script
# Checks Real-time search limits and JavaScript settings
#

echo "🔍 Splunk 문제 진단 (Diagnostic Report)"
echo "========================================"
echo ""

# Issue 1: Real-time Search Limit
echo "📊 Issue 1: Real-time 검색 제한 (Search Limit)"
echo "-------------------------------------------"
echo ""
echo "현재 상태:"
echo "  - 제한: 70개 동시 Real-time 검색"
echo "  - 스킵률: 24.6% (2,031/8,265)"
echo "  - 상태: 🔴 CRITICAL (20% 초과)"
echo ""
echo "❓ 왜 이런 일이?"
echo "  → 70개보다 많은 Real-time 검색이 스케줄되어 있음"
echo "  → 검색 2개 끄면 → 대기 중인 다른 검색이 슬롯 차지 (풍선 효과)"
echo ""

# Issue 2: JavaScript
echo "📊 Issue 2: JavaScript 문제"
echo "-------------------------------------------"
echo ""
echo "❌ 이 둘은 **관계 없습니다**:"
echo ""
echo "  Real-time 검색 제한 ≠ JavaScript 비활성화"
echo ""
echo "  - Real-time 제한: 검색 실행 개수 제한"
echo "  - JavaScript 비활성화: 대시보드 기능 제한"
echo ""
echo "JavaScript 문제 확인 방법:"
echo "  1. Splunk UI → Settings → Server Settings → General Settings"
echo "  2. 또는 /opt/splunk/etc/system/local/web.conf 확인"
echo "  3. enable_javascript = false 인지 확인"
echo ""

# Solution
echo "📊 해결 방법 (Solutions)"
echo "-------------------------------------------"
echo ""
echo "🎯 Real-time 검색 문제 해결:"
echo ""
echo "1️⃣ 급한 경우 (Quick Fix):"
echo "   ./scripts/increase-realtime-limit.sh"
echo "   → 70개 → 140개로 증가"
echo "   → Splunk 재시작 필요"
echo ""
echo "2️⃣ 근본 해결 (Proper Fix):"
echo "   아래 SPL 쿼리로 범인 찾기:"
echo ""
echo "   | rest /services/saved/searches"
echo "   | search is_scheduled=1 realtime_schedule=1 disabled=0"
echo "   | stats count by eai:acl.app"
echo "   | sort -count"
echo ""
echo "   그 다음:"
echo "   - 불필요한 검색 비활성화"
echo "   - Real-time → Scheduled 전환 (5분마다)"
echo ""
echo "🎯 JavaScript 문제 해결:"
echo ""
echo "1️⃣ JavaScript 활성화 필요:"
echo "   configs/dashboards/slack-control-no-js.xml 사용"
echo "   → JavaScript 없이 작동하는 버전"
echo ""
echo "2️⃣ 또는 JavaScript 활성화:"
echo "   Settings → Configuration Files → web.conf"
echo "   [settings]"
echo "   enable_javascript = true"
echo "   → Splunk 재시작"
echo ""

echo "📋 다음 단계 (Next Steps)"
echo "-------------------------------------------"
echo ""
echo "1. Splunk UI에서 SPL 쿼리 실행 → 어떤 앱이 Real-time 검색 많이 만드는지 확인"
echo "2. 결과 보고 → 70개 초과면 증가 스크립트 실행"
echo "3. JavaScript 문제는 별도로 web.conf 확인"
echo ""
